### ISSUE TITLE
Install ipython with python-3.8.1 :/bin/python: No module named Ipython

### ISSUE THREAD

**Issue by Hebin-9527** [Hebin-9527/mage_edu_study#1]
i try to update python-2.7.5 to python-3.8.1
the python-3.8.1 update has successfully
`# python -V
Python 3.8.1`
then i changed the env of yum
vim /usr/bin/yum
#!/usr/bin/python --> #!/usr/bin/python2.7.5
#vim  /usr/libexec/urlgrabber-ext-down
#!/usr/bin/python --> #!/usr/bin/python2.7.5
test the yum install -y net-tools successfully！
# alias ipython='python -m /usr/local/ipython-6.1.0/IPython'
# ipython
/bin/python: Error while finding module specification for '/usr/local/ipython-6.1.0/IPython' (ModuleNotFoundError: No module named '/usr/local/ipython-6')
Is the problem python2.7.5 related？

**Comment by Hebin-9527** [comment]
the above problem has beev solved,but there are new problems.
`# ipython 
Traceback (most recent call last):
  File "/bin/ipython", line 4, in <module>
    from IPython import start_ipython
  File "/usr/Python-3.8.1/lib/python3.8/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/usr/Python-3.8.1/lib/python3.8/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/usr/Python-3.8.1/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 22, in <module>
    from prompt_toolkit.shortcuts import create_prompt_application, create_eventloop, create_prompt_layout, create_output
ImportError: cannot import name 'create_prompt_application' from 'prompt_toolkit.shortcuts' (/usr/Python-3.8.1/lib/python3.8/site-packages/prompt_toolkit/shortcuts/__init__.py)`
